apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-users-config
data:
  application.conf: |-
    port = {{ .Values.userService.port }}
    host = 0.0.0.0
    db-config {
        url = "jdbc:postgresql://{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.postgresql.service.port }}/{{ .Values.database.dbname }}"
        driver = "org.postgresql.Driver"
        pool-size = {{ .Values.userService.poolSize }}
    }

  logback.xml: |-
    <configuration>
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <withJansi>false</withJansi>
            <encoder>
               <pattern>[%thread] %highlight(%-5level) %cyan(%logger{15}) - %msg %X %n</pattern>
            </encoder>
        </appender>
        <root level="DEBUG">
            <appender-ref ref="STDOUT" />
        </root>
    </configuration>
