{
 "title": "Kubernetes dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "User Service - POD Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{pod=~\"first-release-users.*\"} ) by (pod)",
     "legendFormat": "Memory Usage - {{pod}}"
    }
   ]
  },
  {
   "title": "User Service - POD CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{pod=~\"first-release-users-.*\"}[10m])) by (pod)",
     "legendFormat": "CPU Usage - {{pod}}"
    }
   ]
  },
  {
   "title": "PostgreSQL UP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "pg_up", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Postgres Max Transaction duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "pg_stat_activity_max_tx_duration"
    }
   ]
  }
 ]
}